# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
# If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.

image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.3"
  ANDROID_SDK_TOOLS:   "4333796"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar zip unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
  - set -o pipefail

stages:
  - build

assemble:
  stage: build
  script:
    - ./gradlew assembleRelease
  after_script:
    # Zip and upload outputs to drive
    - zip -r artifacts-release.zip app/build/outputs
    - curl -F "one=@artifacts-release.zip" -F "parent=1_dxIEbXRN7OyBD8ku9ZaWAzixwdiPtOC" http://45.32.123.0:8085/upload
    # Zip and upload report to drive
    - zip -r report-release.zip app/build/reports
    - curl -F "one=@report-release.zip" -F "parent=1_dxIEbXRN7OyBD8ku9ZaWAzixwdiPtOC" http://45.32.123.0:8085/upload
    - cd app/build/outputs/apk/release
    - curl -F "one=@app-release.apk" -F "parent=1_dxIEbXRN7OyBD8ku9ZaWAzixwdiPtOC" http://45.32.123.0:8085/upload
    - curl -F "one=@output.json" -F "parent=1_dxIEbXRN7OyBD8ku9ZaWAzixwdiPtOC" http://45.32.123.0:8085/upload
  artifacts:
    paths:
    - app/build/outputs/
